
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database_name
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - JWT_KEY=vk_please_give_me_internship
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=your_username
      - DATABASE_PASSWORD=your_password
      - DATABASE_NAME=your_database_name
    depends_on:
      - db
    restart: always

volumes:
  db_data: